Import('*')

SimObject('CIM.py', \
    sim_objects=['CIMDriver', 'BasicCIM', 'NanoCIM', 'NanoCIMDriver'])

Source('cim_driver.cc')
Source('basic_cim.cc')
Source('nano_cim.cc')
Source('nano_cim_driver.cc')

DebugFlag('CIMDriver')
DebugFlag('BasicCIM')
DebugFlag('NanoCIM')
DebugFlag('NanoCIMDriver')

CompoundFlag('CIMALL', ['CIMDriver','BasicCIM', 'NanoCIM', 'NanoCIMDriver'])